name: Manually send metadata to NFDI4Health
on:
  workflow_dispatch:
  
jobs:
  sync_opencode:
    name: Send metadata to NFDI4Health
    runs-on: ubuntu-latest
    steps:
      - name: Sync Github Open Data repository
        uses: robert-koch-institut/OpenData-Workflows/Send_metadata_to_NFDI4Health@main
        with:
          nfdi4health_client_id: CSH_RKI_CLIENT
          nfdi4health_client_secret: ${{secrets.NFDI4HEALTH_SECRET}}
          nfdi4health_metadata_path: Metadaten/nfdi4health.json
          nfdi4health_authorization_endpoint: "https://sso.studyhub.nfdi4health.de/realms/nfdi4health/protocol/openid-connect/token"
          github_token: ${{secrets.GITHUB_TOKEN}}